#!/bin/bash

export BUILD_PATH=build
export ACCOUNT_PATH=github.com/dsoprea/go-pathfingerprint
export DEPOSIT_PATH=$BUILD_PATH/src/$ACCOUNT_PATH

mkdir -p $DEPOSIT_PATH

rm -fr $DEPOSIT_PATH/internal
rm -fr $DEPOSIT_PATH/commands

cp -r internal $DEPOSIT_PATH
cp -r commands $DEPOSIT_PATH

cd $BUILD_PATH
export GOPATH=`pwd`

go get $ACCOUNT_PATH/commands/pfhash $ACCOUNT_PATH/commands/pflookup
go build $ACCOUNT_PATH/commands/pfhash $ACCOUNT_PATH/commands/pflookup
