#!/bin/bash

export GOPATH=`pwd`/../../../..
COMMAND_PATH=github.com/dsoprea/go-pathfingerprint/commands

mkdir -p bin

go get $COMMAND_PATH/pfhash $COMMAND_PATH/pflookup
go build -o bin/pfhash $COMMAND_PATH/pfhash
go build -o bin/pflookup $COMMAND_PATH/pflookup
